version: "3.9"

services:
  mc-server:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "24454:24454/udp"   # voice chat UDP port
    environment:
      PACKWIZ_URL: "http://host.docker.internal:8080/pack.toml"
      # PACKWIZ_URL: "https://ddsuarez34.github.io/Minecraft-Mods/modpack/pack.toml"
      EULA: "TRUE"
      TYPE: "NEOFORGE"
      MEMORY: 4G
      RCON_ENABLE: "true"
      RCON_PORT: 25575
      RCON_PASSWORD: "${RCON_PASSWORD}"
    healthcheck:
      test: ["CMD", "bash", "-lc", "nc -z localhost 25565"]
      interval: 10s
      retries: 5
    volumes:
      - mc_data:/data

  cloudflared:
    image: cloudflare/cloudflared:latest
    working_dir: /etc/cloudflared
    # point at the same network DNS name "mc-server"
    command: tunnel --config /etc/cloudflared/config.yaml run endor-mc 
    restart: on-failure
    depends_on:
      - mc-server   # ensures ordering, but won’t wait for health
    volumes:
      - ./cloudflared/config.yaml:/etc/cloudflared/config.yaml:ro
      - ./cloudflared/tunnel_credentials.json:/etc/cloudflared/tunnel_credentials.json:ro

  playit:
    image: ghcr.io/playit-cloud/playit-agent:latest
    restart: unless-stopped
    depends_on:
      - mc-server   # ensures ordering, but won’t wait for health
    env_file:
      - ./playit/.env               # contains SECRET_KEY=<your playit.gg API token>
    command: >
        sh -c "
        playit connect \
          RUST_LOG=warn \
          --local-host mc-server \
          --local-port 24454 \
          --remote-port 24454 \
          --protocol udp &
        "

volumes:
  mc_data:
    external: true
