services:
  mc-server:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "24454:24454" # Simple Voice Chat mod UDP port open.
    environment:
      EULA: "TRUE"
      PACKWIZ_URL: "http://host.docker.internal:8080/pack.toml"
      TYPE: "NEOFORGE"          # or FABRIC / omit for vanilla
      MEMORY: 4G 

      # RCON settings
      RCON_ENABLE: "true"
      RCON_PORT: 25575
      RCON_PASSWORD: "${RCON_PASSWORD}"

      #––– Auto-Stop settings –––
      ENABLE_AUTOSTOP: "true"             # turn on auto-stop
      AUTOSTOP_TIMEOUT_INIT: "600"        # secs after start with 0 joins → stop
      AUTOSTOP_TIMEOUT_EST: "1200"        # secs after last disconnect → stop
      AUTOSTOP_PERIOD: "10"               # check-loop period (secs)

    volumes:
      - mc_data:/data

  discord-bot:
    build: ./bot
    depends_on:
      - mc-server
    environment:
      # your Discord bot token
      DISCORD_TOKEN: "${DISCORD_TOKEN}"
      # point at the RCON exposed by mc-server
      RCON_HOST: mc-server
      RCON_PORT: 25575
      RCON_PASSWORD: "${RCON_PASSWORD}"
    restart: on-failure

volumes:
  mc_data:
    name: mc_data