version: "3.9"

services:
  mc-server:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "24454:24454/udp"   # voice chat UDP port
      - "61218:61218/udp"   # voice chat UDP port

    environment:
      PACKWIZ_URL: "http://host.docker.internal:8080/pack.toml"
      # PACKWIZ_URL: "https://ddsuarez34.github.io/Minecraft-Mods/modpack/pack.toml"
      EULA: "TRUE"
      TYPE: "NEOFORGE"
      VERSION:            "1.21.1"      # Minecraft version
      FORGEVERSION:       "21.1.169"    # NeoForge (Forge) version
      MEMORY: 6G
      RCON_ENABLE: "true"
      RCON_PORT: 25575
      RCON_PASSWORD: "${RCON_PASSWORD}"
      ICON: /endor-logo.jpeg
      OVERRIDE_ICON: true
      MOTD: "LARGA VIDA AL PUEBLO, LARGA VIDA A §l§cENDOR§r"
      OPS: |
        ch0rizard
      SPAWN_PROTECTION: 0
      VIEW_DISTANCE: 8
      SIMULATION_DISTANCE: 6
      JVM_OPTS: >
        -XX:InitiatingHeapOccupancyPercent=40
        -XX:G1MixedGCCountTarget=8
        -XX:SurvivorRatio=32
        -XX:+UseStringDeduplication
        -XX:+AlwaysPreTouch
        -XX:MaxMetaspaceSize=512M
        -Xlog:gc*:file=/data/logs/gc.log:time,uptime,tags:filecount=5,filesize=10M

    healthcheck:
      test: ["CMD", "bash", "-lc", "nc -z localhost 25565"]
      interval: 10s
      retries: 5
    volumes:
      - ./data:/data
      - ./assets/endor-logo.jpeg:/endor-logo.jpeg

  cloudflared:
    image: cloudflare/cloudflared:latest
    working_dir: /etc/cloudflared
    # point at the same network DNS name "mc-server"
    command: tunnel --config /etc/cloudflared/config.yaml run endor-mc 
    restart: on-failure
    depends_on:
      - mc-server   # ensures ordering, but won’t wait for health
    volumes:
      - ./cloudflared/config.yaml:/etc/cloudflared/config.yaml:ro
      - ./cloudflared/tunnel_credentials.json:/etc/cloudflared/tunnel_credentials.json:ro
    deploy:
      resources:
        limits:
          memory: 100M  # Hard cap (cloudflared rarely exceeds 50MB)
          cpus: '0.25'  # Max 25% of 1 CPU core
        reservations:
          memory: 50M   # Guaranteed minimum

  playit:
    platform: linux/amd64 # UNCOMMENT if you are on M1/2/3 chip
    image: ghcr.io/playit-cloud/playit-agent:latest
    network_mode: host              # <— use host networking
    restart: unless-stopped
    depends_on:
      - mc-server   # ensures ordering, but won’t wait for health
    env_file:
      - ./playit/.env               # contains SECRET_KEY=<your playit.gg API token>
    deploy:
      resources:
        limits:
          memory: 300M  # Hard cap (playit rarely needs >200MB)
          cpus: '0.5'   # Max 50% of 1 CPU core
        reservations:
          memory: 100M  # Guaranteed minimum

# volumes:
#   mc_data:
#     name: mc_data
