name = "endor"
author = "La Comunidad del Anillo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c869baa76c4c92c3ddd6f79bb9904beaca4cfbc7f0bce651e470724022f2c5fe"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"
