name = "endor"
author = "La Comunidad del Anillo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e963e2c28a06fb8e72045bde3c9ee42e9a70f2ef750401c74d9c5d2fa5679cee"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.164"
