name = "endor_server"
author = "La Comunidad del Anillo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cdee25187877dcfd1b94bc019031ef53ef55780c8fb4752ead59c11cff85815d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.164"
