name = "endor_server"
author = "La Comunidad del Anillo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cbf2dad653ed6dddf4207222552a236289d17b49539237e21ff23735f9dca2de"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.164"
